name: CI

on:
  pull_request:
    branches: 
      - master
  push:
    branches: 
      - master
      - release/*

jobs:

  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: run tests
        run: ./gradlew test

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo TODO
